### ISSUE TITLE
List package at https://gap-packages.github.io/ 

### ISSUE THREAD

**Issue by olexandr-konovalov** [nagygp/IncidenceStructures#1]
We maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help other GAP users and developers to find them.

**Comment by nagygp** [comment]
Hi,

Yes, thank you very much.

Best regards,

Gabor

**Comment by olexandr-konovalov** [comment]
Thanks - done in https://github.com/gap-packages/gap-packages.github.io/commit/8f7ad8876f2f42673599c0bc545c075272d0a593
